export const criteriaByIndicator3: Record<string, { concept: string; criterion: string }[]> = {
  '3.1': [
    { concept: '1', criterion: 'Os espaços de trabalho para docentes em Tempo Integral não viabilizam ações acadêmicas, como planejamento didático-pedagógico.' },
    { concept: '2', criterion: 'Os espaços de trabalho para docentes em Tempo Integral viabilizam ações acadêmicas, como planejamento didático-pedagógico, mas não atendem às necessidades institucionais ou não possuem recursos de tecnologias da informação e comunicação apropriados.' },
    { concept: '3', criterion: 'Os espaços de trabalho para docentes em Tempo Integral viabilizam ações acadêmicas, como planejamento didático-pedagógico, atendem às necessidades institucionais e possuem recursos de tecnologias da informação e comunicação apropriados.' },
    { concept: '4', criterion: 'Os espaços de trabalho para docentes em Tempo Integral viabilizam ações acadêmicas, como planejamento didático-pedagógico, atendem às necessidades institucionais, possuem recursos de tecnologias da informação e comunicação apropriados, e garantem privacidade para uso dos recursos e para o atendimento a discentes e orientandos.' },
    { concept: '5', criterion: 'Os espaços de trabalho para docentes em Tempo Integral viabilizam ações acadêmicas, como planejamento didático-pedagógico, atendem às necessidades institucionais, possuem recursos de tecnologias da informação e comunicação apropriados, garantem privacidade para uso dos recursos, para o atendimento a discentes e orientandos, e para a guarda de material e equipamentos pessoais, com segurança.' }
  ],
  '3.2': [
    { concept: '1', criterion: 'O espaço de trabalho para o coordenador não viabiliza as ações acadêmico-administrativas.' },
    { concept: '2', criterion: 'O espaço de trabalho para o coordenador viabiliza as ações acadêmico-administrativas, mas não possui equipamentos adequados ou não atende às necessidades institucionais.' },
    { concept: '3', criterion: 'O espaço de trabalho para o coordenador viabiliza as ações acadêmico-administrativas, possui equipamentos adequados e atende às necessidades institucionais.' },
    { concept: '4', criterion: 'O espaço de trabalho para o coordenador viabiliza as ações acadêmico-administrativas, possui equipamentos adequados, atende às necessidades institucionais e permite o atendimento de indivíduos ou grupos com privacidade.' },
    { concept: '5', criterion: 'O espaço de trabalho para o coordenador viabiliza as ações acadêmico-administrativas, possui equipamentos adequados, atende às necessidades institucionais, permite o atendimento de indivíduos ou grupos com privacidade e dispõe de infraestrutura tecnológica diferenciada, que possibilita formas distintas de trabalho.' }
  ],
  '3.3': [
    { concept: '1', criterion: 'A sala coletiva de professores não viabiliza o trabalho docente.' },
    { concept: '2', criterion: 'A sala coletiva de professores viabiliza o trabalho docente, mas não possui recursos de tecnologias da informação e comunicação apropriados para o quantitativo de docentes.' },
    { concept: '3', criterion: 'A sala coletiva de professores viabiliza o trabalho docente, apresenta acessibilidade e possui recursos de tecnologias da informação e comunicação apropriados para o quantitativo de docentes.' },
    { concept: '4', criterion: 'A sala coletiva de professores viabiliza o trabalho docente, possui recursos de tecnologias da informação e comunicação apropriados para o quantitativo de docentes e permite o descanso e atividades de lazer e integração.' },
    { concept: '5', criterion: 'A sala coletiva de professores viabiliza o trabalho docente, possui recursos de tecnologias da informação e comunicação apropriados para o quantitativo de docentes, permite o descanso e atividades de lazer e integração e dispõe de apoio técnico-administrativo próprio e espaço para a guarda de equipamentos e materiais.' }
  ],
  '3.4': [
    { concept: '1', criterion: 'As salas de aula não atendem às necessidades institucionais e do curso.' },
    { concept: '2', criterion: 'As salas de aula atendem às necessidades institucionais e do curso, mas não apresentam manutenção periódica, ou conforto, ou disponibilidade de recursos de tecnologias da informação e comunicação adequados às atividades a serem desenvolvidas.' },
    { concept: '3', criterion: 'As salas de aula atendem às necessidades institucionais e do curso, apresentando manutenção periódica, conforto e disponibilidade de recursos de tecnologias da informação e comunicação adequados às atividades a serem desenvolvidas.' },
    { concept: '4', criterion: 'As salas de aula atendem às necessidades institucionais e do curso, apresentando manutenção periódica, conforto, disponibilidade de recursos de tecnologias da informação e comunicação adequados às atividades a serem desenvolvidas e flexibilidade relacionada às configurações espaciais, oportunizando distintas situações de ensino-aprendizagem.' },
    { concept: '5', criterion: 'As salas de aula atendem às necessidades institucionais e do curso, apresentando manutenção periódica, conforto, disponibilidade de recursos de tecnologias da informação e comunicação adequados às atividades a serem desenvolvidas, flexibilidade relacionada às configurações espaciais, oportunizando distintas situações de ensino-aprendizagem, e possuem outros recursos cuja utilização é comprovadamente exitosa.' }
  ],
  '3.5': [
    { concept: '1', criterion: 'O laboratório de informática, ou outro meio de acesso a equipamentos de informática pelos discentes, não atende às necessidades institucionais e do curso.' },
    { concept: '2', criterion: 'O laboratório de informática, ou outro meio de acesso a equipamentos de informática pelos discentes, atende às necessidades institucionais e do curso, mas não em relação à disponibilidade de equipamentos, ao conforto, à estabilidade e velocidade de acesso à internet, à rede sem fio ou à adequação do espaço físico.' },
    { concept: '3', criterion: 'O laboratório de informática, ou outro meio de acesso a equipamentos de informática pelos discentes, atende às necessidades institucionais e do curso em relação à disponibilidade de equipamentos, ao conforto, à estabilidade e velocidade de acesso à internet, à rede sem fio e à adequação do espaço físico.' },
    { concept: '4', criterion: 'O laboratório de informática, ou outro meio de acesso a equipamentos de informática pelos discentes, atende às necessidades institucionais e do curso em relação à disponibilidade de equipamentos, ao conforto, à estabilidade e velocidade de acesso à internet, à rede sem fio e à adequação do espaço físico, e possui hardware e software atualizados.' },
    { concept: '5', criterion: 'O laboratório de informática, ou outro meio de acesso a equipamentos de informática pelos discentes, atende às necessidades institucionais e do curso em relação à disponibilidade de equipamentos, ao conforto, à estabilidade e velocidade de acesso à internet, à rede sem fio e à adequação do espaço físico, possui hardware e software atualizados e passa por avaliação periódica de sua adequação, qualidade e pertinência.' }
  ],
  '3.6': [
    { concept: '1', criterion: 'O acervo físico não está tombado e informatizado; ou o virtual não possui contrato que garante o acesso ininterrupto pelos usuários; ou pelo menos um deles não está registrado em nome da IES. Ou o acervo da bibliografia básica não é adequado em relação às unidades curriculares e aos conteúdos descritos no PPC ou não está atualizado, considerando a natureza das UC. Ou, ainda, não está referendado por relatório de adequação, ou não está assinado pelo NDE, comprovando a compatibilidade, em cada bibliografia básica da UC, entre o número de vagas autorizadas (do próprio curso e de outros que utilizem os títulos) e a quantidade de exemplares por título (ou assinatura de acesso) disponível no acervo.' },
    { concept: '2', criterion: 'O acervo físico está tombado e informatizado, o virtual possui contrato que garante o acesso ininterrupto pelos usuários e ambos estão registrados em nome da IES. O acervo da bibliografia básica é adequado em relação às unidades curriculares e aos conteúdos descritos no PPC e está atualizado, considerando a natureza das UC. Porém, não está referendado por relatório de adequação, ou não está assinado pelo NDE, comprovando a compatibilidade, em cada bibliografia básica da UC, entre o número de vagas autorizadas (do próprio curso e de outros que utilizem os títulos) e a quantidade de exemplares por título (ou assinatura de acesso) disponível no acervo. Ou, nos casos dos títulos virtuais, não há garantia de acesso físico na IES, com instalações e recursos tecnológicos que atendem à demanda e à oferta ininterrupta via internet, ou de ferramentas de acessibilidade ou de soluções de apoio à leitura, estudo e aprendizagem.' },
    { concept: '3', criterion: 'O acervo físico está tombado e informatizado, o virtual possui contrato que garante o acesso ininterrupto pelos usuários e ambos estão registrados em nome da IES. O acervo da bibliografia básica é adequado em relação às unidades curriculares e aos conteúdos descritos no PPC e está atualizado, considerando a natureza das UC. Da mesma forma, está referendado por relatório de adequação, assinado pelo NDE, comprovando a compatibilidade, em cada bibliografia básica da UC, entre o número de vagas autorizadas (do próprio curso e de outros que utilizem os títulos) e a quantidade de exemplares por título (ou assinatura de acesso) disponível no acervo. Nos casos dos títulos virtuais, há garantia de acesso físico na IES, com instalações e recursos tecnológicos que atendem à demanda e à oferta ininterrupta via internet, bem como de ferramentas de acessibilidade e de soluções de apoio à leitura, estudo e aprendizagem.' },
    { concept: '4', criterion: 'O acervo físico está tombado e informatizado, o virtual possui contrato que garante o acesso ininterrupto pelos usuários e ambos estão registrados em nome da IES. O acervo da bibliografia básica é adequado em relação às unidades curriculares e aos conteúdos descritos no PPC e está atualizado, considerando a natureza das UC. Da mesma forma, está referendado por relatório de adequação, assinado pelo NDE, comprovando a compatibilidade, em cada bibliografia básica da UC, entre o número de vagas autorizadas (do próprio curso e de outros que utilizem os títulos) e a quantidade de exemplares por título (ou assinatura de acesso) disponível no acervo. Nos casos dos títulos virtuais, há garantia de acesso físico na IES, com instalações e recursos tecnológicos que atendem à demanda e à oferta ininterrupta via internet, bem como de ferramentas de acessibilidade e de soluções de apoio à leitura, estudo e aprendizagem. O acervo possui exemplares, ou assinaturas de acesso virtual, de periódicos especializados que suplementam o conteúdo administrado nas UC.' },
    { concept: '5', criterion: 'O acervo físico está tombado e informatizado, o virtual possui contrato que garante o acesso ininterrupto pelos usuários e ambos estão registrados em nome da IES. O acervo da bibliografia básica é adequado em relação às unidades curriculares e aos conteúdos descritos no PPC e está atualizado, considerando a natureza das UC. Da mesma forma, está referendado por relatório de adequação, assinado pelo NDE, comprovando a compatibilidade, em cada bibliografia básica da UC, entre o número de vagas autorizadas (do próprio curso e de outros que utilizem os títulos) e a quantidade de exemplares por título (ou assinatura de acesso) disponível no acervo. Nos casos dos títulos virtuais, há garantia de acesso físico na IES, com instalações e recursos tecnológicos que atendem à demanda e à oferta ininterrupta via internet, bem como de ferramentas de acessibilidade e de soluções de apoio à leitura, estudo e aprendizagem. O acervo possui exemplares, ou assinaturas de acesso virtual, de periódicos especializados que suplementam o conteúdo administrado nas UC. O acervo é gerenciado de modo a atualizar a quantidade de exemplares e/ou assinaturas de acesso mais demandadas, sendo adotado plano de contingência para a garantia do acesso e do serviço.' }
  ],
  '3.7': [
    { concept: '1', criterion: 'O acervo físico não está tombado e informatizado; ou o virtual não possui contrato que garante o acesso ininterrupto pelos usuários; ou pelo menos um deles não está registrado em nome da IES. Ou o acervo da bibliografia complementar não é adequado em relação às unidades curriculares e aos conteúdos descritos no PPC ou não está atualizado, considerando a natureza das UC. Ou, ainda, não está referendado por relatório de adequação, ou não está assinado pelo NDE, comprovando a compatibilidade, em cada bibliografia básica da UC, entre o número de vagas autorizadas (do próprio curso e de outros que utilizem os títulos) e a quantidade de exemplares por título (ou assinatura de acesso) disponível no acervo.' },
    { concept: '2', criterion: 'O acervo físico está tombado e informatizado, o virtual possui contrato que garante o acesso ininterrupto pelos usuários e ambos estão registrados em nome da IES. O acervo da bibliografia complementar é adequado em relação às unidades curriculares e aos conteúdos descritos no PPC e está atualizado, considerando a natureza das UC. Porém, não está referendado por relatório de adequação, ou não está assinado pelo NDE, comprovando a compatibilidade, em cada bibliografia complementar da UC, entre o número de vagas autorizadas (do próprio curso e de outros que utilizem os títulos) e a quantidade de exemplares por título (ou assinatura de acesso) disponível no acervo. Ou, nos casos dos títulos virtuais, não há garantia de acesso físico na IES, com instalações e recursos tecnológicos que atendem à demanda e à oferta ininterrupta via internet, ou de ferramentas de acessibilidade ou de soluções de apoio à leitura, estudo e aprendizagem.' },
    { concept: '3', criterion: 'O acervo físico está tombado e informatizado, o virtual possui contrato que garante o acesso ininterrupto pelos usuários e ambos estão registrados em nome da IES. O acervo da bibliografia complementar é adequado em relação às unidades curriculares e aos conteúdos descritos no PPC e está atualizado, considerando a natureza das UC. Da mesma forma, está referendado por relatório de adequação, assinado pelo NDE, comprovando a compatibilidade, em cada bibliografia complementar da UC, entre o número de vagas autorizadas (do próprio curso e de outros que utilizem os títulos) e a quantidade de exemplares por título (ou assinatura de acesso) disponível no acervo. Nos casos dos títulos virtuais, há garantia de acesso físico na IES, com instalações e recursos tecnológicos que atendem à demanda e à oferta ininterrupta via internet, bem como de ferramentas de acessibilidade e de soluções de apoio à leitura, estudo e aprendizagem.' },
    { concept: '4', criterion: 'O acervo físico está tombado e informatizado, o virtual possui contrato que garante o acesso ininterrupto pelos usuários e ambos estão registrados em nome da IES. O acervo da bibliografia complementar é adequado em relação às unidades curriculares e aos conteúdos descritos no PPC e está atualizado, considerando a natureza das UC. Da mesma forma, está referendado por relatório de adequação, assinado pelo NDE, comprovando a compatibilidade, em cada bibliografia complementar da UC, entre o número de vagas autorizadas (do próprio curso e de outros que utilizem os títulos) e a quantidade de exemplares por título (ou assinatura de acesso) disponível no acervo. Nos casos dos títulos virtuais, há garantia de acesso físico na IES, com instalações e recursos tecnológicos que atendem à demanda e à oferta ininterrupta via internet, bem como de ferramentas de acessibilidade e de soluções de apoio à leitura, estudo e aprendizagem. O acervo possui exemplares, ou assinaturas de acesso virtual, de periódicos especializados que complementam o conteúdo administrado nas UC.' },
    { concept: '5', criterion: 'O acervo físico está tombado e informatizado, o virtual possui contrato que garante o acesso ininterrupto pelos usuários e ambos estão registrados em nome da IES. O acervo da bibliografia complementar é adequado em relação às unidades curriculares e aos conteúdos descritos no PPC e está atualizado, considerando a natureza das UC. Da mesma forma, está referendado por relatório de adequação, assinado pelo NDE, comprovando a compatibilidade, em cada bibliografia complementar da UC, entre o número de vagas autorizadas (do próprio curso e de outros que utilizem os títulos) e a quantidade de exemplares por título (ou assinatura de acesso) disponível no acervo. Nos casos dos títulos virtuais, há garantia de acesso físico na IES, com instalações e recursos tecnológicos que atendem à demanda e à oferta ininterrupta via internet, bem como de ferramentas de acessibilidade e de soluções de apoio à leitura, estudo e aprendizagem. O acervo possui exemplares, ou assinaturas de acesso virtual, de periódicos especializados que complementam o conteúdo administrado nas UC. O acervo é gerenciado de modo a atualizar a quantidade de exemplares e/ou assinaturas de acesso mais demandadas, sendo adotado plano de contingência para a garantia do acesso e do serviço.' }
  ],
  '3.8': [
    { concept: '1', criterion: 'Os laboratórios didáticos não atendem às necessidades do curso, de acordo com o PPC e com as respectivas normas de funcionamento.' },
    { concept: '2', criterion: 'Os laboratórios didáticos atendem às necessidades do curso, de acordo com o PPC e com as respectivas normas de funcionamento, utilização e segurança, mas não apresentam conforto, manutenção periódica, serviços de apoio técnico ou disponibilidade de recursos de tecnologias da informação e comunicação adequados às atividades a serem desenvolvidas, ou não possuem quantidade de insumos, materiais ou equipamentos condizentes com os espaços físicos e o número de vagas.' },
    { concept: '3', criterion: 'Os laboratórios didáticos atendem às necessidades do curso, de acordo com o PPC e com as respectivas normas de funcionamento, utilização e segurança, apresentam conforto, manutenção periódica, serviços de apoio técnico e disponibilidade de recursos de tecnologias da informação e comunicação adequados às atividades a serem desenvolvidas, e possuem quantidade de insumos, materiais e equipamentos condizentes com os espaços físicos e o número de vagas.' },
    { concept: '4', criterion: 'Os laboratórios didáticos atendem às necessidades do curso, de acordo com o PPC e com as respectivas normas de funcionamento, utilização e segurança, apresentam conforto, manutenção periódica, serviços de apoio técnico e disponibilidade de recursos de tecnologias da informação e comunicação adequados às atividades a serem desenvolvidas, e possuem quantidade de insumos, materiais e equipamentos condizentes com os espaços físicos e o número de vagas, havendo, ainda, avaliação periódica quanto às demandas, aos serviços prestados e à qualidade dos laboratórios.' },
    { concept: '5', criterion: 'Os laboratórios didáticos atendem às necessidades do curso, de acordo com o PPC e com as respectivas normas de funcionamento, utilização e segurança, apresentam conforto, manutenção periódica, serviços de apoio técnico e disponibilidade de recursos de tecnologias da informação e comunicação adequados às atividades a serem desenvolvidas, e possuem quantidade de insumos, materiais e equipamentos condizentes com os espaços físicos e o número de vagas, havendo, ainda, avaliação periódica quanto às demandas, aos serviços prestados e à qualidade dos laboratórios, sendo os resultados utilizados pela gestão acadêmica para planejar o incremento da qualidade do atendimento, da demanda existente e futura e das aulas ministradas.' }
  ],
  '3.9': [
    { concept: '1', criterion: 'Os laboratórios didáticos não atendem às necessidades do curso, de acordo com o PPC e com as respectivas normas de funcionamento.' },
    { concept: '2', criterion: 'Os laboratórios didáticos atendem às necessidades do curso, de acordo com o PPC e com as respectivas normas de funcionamento, utilização e segurança, mas não apresentam conforto, manutenção periódica, serviços de apoio técnico ou disponibilidade de recursos de tecnologias da informação e comunicação adequados às atividades a serem desenvolvidas, ou não possuem quantidade de insumos, materiais ou equipamentos condizentes com os espaços físicos e o número de vagas.' },
    { concept: '3', criterion: 'Os laboratórios didáticos atendem às necessidades do curso, de acordo com o PPC e com as respectivas normas de funcionamento, utilização e segurança, apresentam conforto, manutenção periódica, serviços de apoio técnico e disponibilidade de recursos de tecnologias da informação e comunicação adequados às atividades a serem desenvolvidas, e possuem quantidade de insumos, materiais e equipamentos condizentes com os espaços físicos e o número de vagas.' },
    { concept: '4', criterion: 'Os laboratórios didáticos atendem às necessidades do curso, de acordo com o PPC e com as respectivas normas de funcionamento, utilização e segurança, apresentam conforto, manutenção periódica, serviços de apoio técnico e disponibilidade de recursos de tecnologias da informação e comunicação adequados às atividades a serem desenvolvidas, e possuem quantidade de insumos, materiais e equipamentos condizentes com os espaços físicos e o número de vagas, havendo, ainda, avaliação periódica quanto às demandas, aos serviços prestados e à qualidade dos laboratórios.' },
    { concept: '5', criterion: 'Os laboratórios didáticos atendem às necessidades do curso, de acordo com o PPC e com as respectivas normas de funcionamento, utilização e segurança, apresentam conforto, manutenção periódica, serviços de apoio técnico e disponibilidade de recursos de tecnologias da informação e comunicação adequados às atividades a serem desenvolvidas, e possuem quantidade de insumos, materiais e equipamentos condizentes com os espaços físicos e o número de vagas, havendo, ainda, avaliação periódica quanto às demandas, aos serviços prestados e à qualidade dos laboratórios, sendo os resultados utilizados pela gestão acadêmica para planejar o incremento da qualidade do atendimento, da demanda existente e futura e das aulas ministradas.' }
  ],
  '3.10': [
    { concept: '1', criterion: 'Não há laboratórios específicos e multidisciplinares em conformidade com as DCN.' },
    { concept: '2', criterion: 'Há laboratórios específicos e multidisciplinares, em conformidade com as DCN, que permitem a abordagem dos diferentes aspectos celulares e moleculares das ciências da vida.' },
    { concept: '3', criterion: 'Há laboratórios específicos e multidisciplinares, em conformidade com as DCN, que permitem a abordagem dos diferentes aspectos celulares e moleculares das ciências da vida e atendem ao PPC.' },
    { concept: '4', criterion: 'Há laboratórios específicos e multidisciplinares, em conformidade com as DCN, que permitem a abordagem dos diferentes aspectos celulares e moleculares das ciências da vida, atendem ao PPC e possuem recursos e insumos necessários para atender à demanda discente.' },
    { concept: '5', criterion: 'Há laboratórios específicos e multidisciplinares, em conformidade com as DCN, que permitem a abordagem dos diferentes aspectos celulares e moleculares das ciências da vida, atendem ao PPC, possuem recursos e insumos necessários para atender à demanda discente e apresentam recursos tecnológicos comprovadamente inovadores.' }
  ],
  '3.11': [
    { concept: '1', criterion: 'Não há laboratórios de habilidades da atividade médica ou de saúde em conformidade com o PPC.' },
    { concept: '2', criterion: 'Há laboratórios de habilidades da atividade médica ou de saúde em conformidade com o PPC, mas não permitem a capacitação dos discentes nas diversas competências desenvolvidas nas diferentes fases do curso.' },
    { concept: '3', criterion: 'Há laboratórios de habilidades da atividade médica ou de saúde, em conformidade com o PPC, que permitem a capacitação dos discentes nas diversas competências desenvolvidas nas diferentes fases do curso.' },
    { concept: '4', criterion: 'Há laboratórios de habilidades da atividade médica ou de saúde, em conformidade com o PPC, que permitem a capacitação dos discentes nas diversas competências desenvolvidas nas diferentes fases do curso, com recursos tecnológicos.' },
    { concept: '5', criterion: 'Há laboratórios de habilidades da atividade médica ou de saúde, em conformidade com o PPC, que permitem a capacitação dos discentes nas diversas competências desenvolvidas nas diferentes fases do curso, com recursos tecnológicos comprovadamente inovadores.' }
  ],
  '3.12': [
    { concept: '1', criterion: 'A IES não conta com unidade(s) hospitalar(es), própria(s) ou conveniada(s), garantida(s) legalmente por período determinado.' },
    { concept: '2', criterion: 'A IES conta com unidade(s) hospitalar(es), própria(s) ou conveniada(s), garantida(s) legalmente por período determinado, mas que não apresenta(m) condições para a formação do estudante da área de saúde.' },
    { concept: '3', criterion: 'A IES conta com unidade(s) hospitalar(es), própria(s) ou conveniada(s), garantida(s) legalmente por período determinado, que apresenta(m) condições para a formação do estudante da área de saúde.' },
    { concept: '4', criterion: 'A IES conta com unidade(s) hospitalar(es), própria(s) ou conveniada(s), garantida(s) legalmente por período determinado, que apresenta(m) condições para a formação do estudante da área de saúde e estabelece(m) sistema de referência e contrarreferência.' },
    { concept: '5', criterion: 'A IES conta com unidade(s) hospitalar(es), própria(s) ou conveniada(s), garantida(s) legalmente por período determinado, que apresenta(m) condições para a formação do estudante da área de saúde, estabelece(m) sistema de referência e contrarreferência e favorece(m) práticas interdisciplinares e interprofissionais na atenção à saúde.' }
  ],
  '3.13': [
    { concept: '1', criterion: 'O biotério não atende às necessidades práticas de ensino.' },
    { concept: '2', criterion: 'O biotério atende às necessidades práticas do ensino, mas não possui insumos necessários à demanda docente e discente ou não apresenta protocolos de experimentos de acordo com as normas internacionais vigentes.' },
    { concept: '3', criterion: 'O biotério atende às necessidades práticas do ensino, possuindo insumos necessários à demanda docente e discente e apresentando protocolos de experimentos de acordo com as normas internacionais vigentes.' },
    { concept: '4', criterion: 'O biotério atende às necessidades práticas do ensino, possuindo insumos necessários à demanda docente e discente e apresentando protocolos de experimentos de acordo com as normas internacionais vigentes e suporte técnico e experimental.' },
    { concept: '5', criterion: 'O biotério atende às necessidades práticas do ensino, possuindo insumos necessários à demanda docente e discente e apresentando protocolos de experimentos de acordo com as normas internacionais vigentes e suporte técnico, experimental e pedagógico.' }
  ],
  '3.14': [
    { concept: '1', criterion: 'Não há processo de controle de produção ou distribuição de material didático.' },
    { concept: '2', criterion: 'O processo de controle de produção ou distribuição de material didático não está formalizado ou não atende à demanda.' },
    { concept: '3', criterion: 'O processo de controle de produção ou distribuição de material didático está formalizado, atende à demanda e possui plano de contingência para a garantia de continuidade de funcionamento.' },
    { concept: '4', criterion: 'O processo de controle de produção ou distribuição de material didático está formalizado, atende à demanda e possui plano de contingência para a garantia de continuidade de funcionamento e dispõe de um sistema informatizado de acompanhamento para gerenciamento dos processos.' },
    { concept: '5', criterion: 'O processo de controle de produção ou distribuição de material didático está formalizado, atende à demanda e possui plano de contingência para a garantia de continuidade de funcionamento e dispõe de um sistema informatizado de acompanhamento para gerenciamento dos processos, com uso de indicadores bem definidos.' }
  ],
  '3.15': [
    { concept: '1', criterion: 'O Núcleo de Práticas Jurídicas não está implantado ou não possui regulamento específico destinado à realização de práticas jurídicas simuladas ou arbitragem, negociação, conciliação, mediação e atividades jurídicas reais.' },
    { concept: '2', criterion: 'O Núcleo de Práticas Jurídicas possui regulamento específico destinado à realização de práticas jurídicas simuladas e arbitragem, negociação, conciliação, mediação e atividades jurídicas reais e oferta visitas orientadas, mas não atende às demandas do curso.' },
    { concept: '3', criterion: 'O Núcleo de Práticas Jurídicas possui regulamento específico destinado à realização de práticas jurídicas simuladas e de arbitragem, negociação, conciliação, mediação e atividades jurídicas reais e oferta visitas orientadas, atendendo às demandas do curso e buscando a interdisciplinaridade das matérias legais.' },
    { concept: '4', criterion: 'O Núcleo de Práticas Jurídicas possui regulamento específico destinado à realização de práticas jurídicas simuladas e de arbitragem, negociação, conciliação, mediação e atividades jurídicas reais e oferta visitas orientadas, atendendo às demandas do curso e buscando a interdisciplinaridade das matérias legais, havendo avaliação periódica quanto ao atendimento da demanda do curso pelo Núcleo de Práticas Jurídicas em suas atividades básicas.' },
    { concept: '5', criterion: 'O Núcleo de Práticas Jurídicas possui regulamento específico destinado à realização de práticas jurídicas simuladas e de arbitragem, negociação, conciliação, mediação e atividades jurídicas reais e oferta visitas orientadas, atendendo às demandas do curso e buscando a interdisciplinaridade das matérias legais, havendo avaliação periódica quanto ao atendimento da demanda do curso pelo Núcleo de Práticas Jurídicas em suas atividades básicas, também utilizada em processos de planejamento para o adequado atendimento da demanda existente.' }
  ],
  '3.16': [
    { concept: '1', criterion: 'Não há Comitê de Ética em Pesquisa (CEP).' },
    { concept: '2', criterion: 'O Comitê de Ética em Pesquisa não está homologado pela CONEP.' },
    { concept: '3', criterion: 'O Comitê de Ética em Pesquisa (CEP) está homologado pela CONEP e pertence a instituição parceira.' },
    { concept: '4', criterion: 'O Comitê de Ética em Pesquisa (CEP) está homologado pela CONEP e pertence à própria instituição.' },
    { concept: '5', criterion: 'O Comitê de Ética em Pesquisa (CEP) está homologado pela CONEP, pertence à própria instituição e presta atendimento a instituições parceiras.' }
  ],
  '3.17': [
    { concept: '1', criterion: 'Não há Comitê de Ética na Utilização de Animais (CEUA).' },
    { concept: '2', criterion: 'O Comitê de Ética na Utilização de Animais (CEUA) não está homologado pela CONEP.' },
    { concept: '3', criterion: 'O Comitê de Ética na Utilização de Animais (CEUA) está homologado pela CONEP e pertence a instituição parceira.' },
    { concept: '4', criterion: 'O Comitê de Ética na Utilização de Animais (CEUA) está homologado pela CONEP e pertence à própria instituição.' },
    { concept: '5', criterion: 'O Comitê de Ética na Utilização de Animais (CEUA) está homologado pela CONEP, pertence à própria instituição e presta atendimento a instituições parceiras.' }
  ],
  '3.18': [
    { concept: '1', criterion: 'Não há ambientes profissionais articulados com a sede ou com os polos.' },
    { concept: '2', criterion: 'Os ambientes profissionais estão articulados com a sede ou com os polos onde há oferta do curso, mas não atendem aos objetivos constantes no PPC.' },
    { concept: '3', criterion: 'Os ambientes profissionais estão articulados com a sede ou com os polos onde há oferta do curso e atendem aos objetivos constantes no PPC, considerando a função de espaços complementares para práticas laboratoriais e/ou profissionais.' },
    { concept: '4', criterion: 'Os ambientes profissionais estão articulados com a sede ou com os polos onde há oferta do curso e atendem aos objetivos constantes no PPC, considerando a função de espaços complementares para práticas laboratoriais e/ou profissionais que possibilitam experiências diferenciadas de aprendizagem.' },
    { concept: '5', criterion: 'Os ambientes profissionais estão articulados com a sede ou com os polos onde há oferta do curso e atendem aos objetivos constantes no PPC, considerando a função de espaços complementares para práticas laboratoriais e/ou profissionais que possibilitam experiências diferenciadas de aprendizagem, as quais passam por avaliações periódicas devidamente documentadas, que resultam em ações de melhoria contínua.' }
  ]
};
