export const criteriaByIndicator2: Record<string, { concept: string; criterion: string }[]> = {
  "2.1": [
    { concept: "1", criterion: "Não há NDE; ou o NDE possui menos de 5 docentes do curso; ou menos de 20% de seus membros atuam em regime de tempo integral ou parcial; ou menos de 60% de seus membros possuem titulação stricto sensu." },
    { concept: "2", criterion: "O NDE possui, no mínimo, 5 docentes do curso; seus membros atuam em regime de tempo integral ou parcial (mínimo de 20% em tempo integral); pelo menos 60% de seus membros possuem titulação stricto sensu; mas não atua no acompanhamento, na consolidação ou na atualização do PPC." },
    { concept: "3", criterion: "O NDE possui, no mínimo, 5 docentes do curso; seus membros atuam em regime de tempo integral ou parcial (mínimo de 20% em tempo integral); pelo menos 60% de seus membros possuem titulação stricto sensu; e atua no acompanhamento, na consolidação e na atualização do PPC." },
    { concept: "4", criterion: "O NDE possui, no mínimo, 5 docentes do curso; seus membros atuam em regime de tempo integral ou parcial (mínimo de 20% em tempo integral); pelo menos 60% de seus membros possuem titulação stricto sensu; tem o coordenador de curso como integrante; atua no acompanhamento, na consolidação e na atualização do PPC, realizando estudos e atualização periódica, verificando o impacto do sistema de avaliação de aprendizagem na formação do estudante e analisando a adequação do perfil do egresso, considerando as DCN e as novas demandas do mundo do trabalho." },
    { concept: "5", criterion: "O NDE possui, no mínimo, 5 docentes do curso; seus membros atuam em regime de tempo integral ou parcial (mínimo de 20% em tempo integral); pelo menos 60% de seus membros possuem titulação stricto sensu; tem o coordenador de curso como integrante; atua no acompanhamento, na consolidação e na atualização do PPC, realizando estudos e atualização periódica, verificando o impacto do sistema de avaliação de aprendizagem na formação do estudante e analisando a adequação do perfil do egresso, considerando as DCN e as novas demandas do mundo do trabalho; e mantém parte de seus membros desde o último ato regulatório." }
  ],
  "2.2": [
    { concept: "1", criterion: "Não há equipe multidisciplinar estabelecida." },
    { concept: "2", criterion: "A equipe multidisciplinar não está em consonância com o PPC, ou não é constituída por profissionais de diferentes áreas do conhecimento, ou não é responsável pela concepção, produção e disseminação de tecnologias, metodologias e os recursos educacionais para a educação a distância." },
    { concept: "3", criterion: "A equipe multidisciplinar, estabelecida em consonância com o PPC, é constituída por profissionais de diferentes áreas do conhecimento e é responsável pela concepção, produção e disseminação de tecnologias, metodologias e os recursos educacionais para a educação a distância." },
    { concept: "4", criterion: "A equipe multidisciplinar, estabelecida em consonância com o PPC, é constituída por profissionais de diferentes áreas do conhecimento, é responsável pela concepção, produção e disseminação de tecnologias, metodologias e os recursos educacionais para a educação a distância e possui plano de ação documentado e implementado." },
    { concept: "5", criterion: "A equipe multidisciplinar, estabelecida em consonância com o PPC, é constituída por profissionais de diferentes áreas do conhecimento, é responsável pela concepção, produção e disseminação de tecnologias, metodologias e os recursos educacionais para a educação a distância e possui plano de ação documentado e implementado e processos de trabalho formalizados." }
  ],
  "2.3": [
    { concept: "1", criterion: "A atuação do coordenador não está de acordo com o PPC." },
    { concept: "2", criterion: "A atuação do coordenador está de acordo com o PPC, mas não atende à demanda existente, considerando a gestão do curso, a relação com os docentes e discentes, com tutores e equipe multidisciplinar (quando for o caso) ou a representatividade nos colegiados superiores." },
    { concept: "3", criterion: "A atuação do coordenador está de acordo com o PPC e atende à demanda existente, considerando a gestão do curso, a relação com os docentes e discentes, com tutores e equipe multidisciplinar (quando for o caso) e a representatividade nos colegiados superiores." },
    { concept: "4", criterion: "A atuação do coordenador está de acordo com o PPC, atende à demanda existente, considerando a gestão do curso, a relação com os docentes e discentes, com tutores e equipe multidisciplinar (quando for o caso) e a representatividade nos colegiados superiores, é pautada em um plano de ação documentado e compartilhado e dispõe de indicadores de desempenho da coordenação disponíveis e públicos." },
    { concept: "5", criterion: "A atuação do coordenador está de acordo com o PPC, atende à demanda existente, considerando a gestão do curso, a relação com os docentes e discentes, com tutores e equipe multidisciplinar (quando for o caso) e a representatividade nos colegiados superiores, é pautada em um plano de ação documentado e compartilhado, dispõe de indicadores de desempenho da coordenação disponíveis e públicos e administra a potencialidade do corpo docente do seu curso, favorecendo a integração e a melhoria contínua." }
  ],
  "2.4": [
    { concept: "1", criterion: "O regime de trabalho do coordenador não é de tempo parcial nem integral." },
    { concept: "2", criterion: "O regime de trabalho do coordenador é de tempo parcial, mas não permite o atendimento da demanda existente, considerando a gestão do curso, a relação com os docentes, discentes, tutores e equipe multidisciplinar (quando for o caso) e a representatividade nos colegiados superiores." },
    { concept: "3", criterion: "O regime de trabalho do coordenador é de tempo parcial ou integral e permite o atendimento da demanda existente, considerando a gestão do curso, a relação com os docentes, discentes, tutores e equipe multidisciplinar (quando for o caso) e a representatividade nos colegiados superiores." },
    { concept: "4", criterion: "O regime de trabalho do coordenador é de tempo integral e permite o atendimento da demanda existente, considerando a gestão do curso, a relação com os docentes, discentes, tutores e equipe multidisciplinar (quando for o caso) e a representatividade nos colegiados superiores, por meio de um plano de ação documentado e compartilhado, com indicadores disponíveis e públicos com relação ao desempenho da coordenação." },
    { concept: "5", criterion: "O regime de trabalho do coordenador é de tempo integral e permite o atendimento da demanda existente, considerando a gestão do curso, a relação com os docentes, discentes, tutores e equipe multidisciplinar (quando for o caso) e a representatividade nos colegiados superiores, por meio de um plano de ação documentado e compartilhado, com indicadores disponíveis e públicos com relação ao desempenho da coordenação, e proporciona a administração da potencialidade do corpo docente do seu curso, favorecendo a integração e a melhoria contínua." }
  ],
  "2.5": [
    { concept: "1", criterion: "O corpo docente apresenta os conteúdos dos componentes curriculares sem abordar a sua relevância para a atuação profissional e acadêmica do discente." },
    { concept: "2", criterion: "O corpo docente descreve os conteúdos dos componentes curriculares, abordando a sua relevância para a atuação profissional e acadêmica do discente, mas não fomenta o raciocínio crítico com base em literatura atualizada." },
    { concept: "3", criterion: "O corpo docente analisa os conteúdos dos componentes curriculares, abordando a sua relevância para a atuação profissional e acadêmica do discente, e fomenta o raciocínio crítico com base em literatura atualizada, para além da bibliografia proposta." },
    { concept: "4", criterion: "O corpo docente analisa os conteúdos dos componentes curriculares, abordando a sua relevância para a atuação profissional e acadêmica do discente, fomenta o raciocínio crítico com base em literatura atualizada, para além da bibliografia proposta, e proporciona o acesso a conteúdos de pesquisa de ponta, relacionando-os aos objetivos das disciplinas e ao perfil do egresso." },
    { concept: "5", criterion: "O corpo docente analisa os conteúdos dos componentes curriculares, abordando a sua relevância para a atuação profissional e acadêmica do discente, fomenta o raciocínio crítico com base em literatura atualizada, para além da bibliografia proposta, proporciona o acesso a conteúdos de pesquisa de ponta, relacionando-os aos objetivos das disciplinas e ao perfil do egresso, e incentiva a produção do conhecimento, por meio de grupos de estudo ou de pesquisa e da publicação." }
  ],
  "2.6": [
    { concept: "1", criterion: "O regime de trabalho do corpo docente não permite o atendimento da demanda existente, considerando a dedicação à docência, o atendimento aos discentes, a participação no colegiado, o planejamento didático, a preparação e correção das avaliações de aprendizagem." },
    { concept: "2", criterion: "O regime de trabalho do corpo docente permite um atendimento limitado da demanda existente, considerando a dedicação à docência, o atendimento aos discentes, a participação no colegiado, o planejamento didático e a preparação e correção das avaliações de aprendizagem." },
    { concept: "3", criterion: "O regime de trabalho do corpo docente permite o atendimento integral da demanda existente, considerando a dedicação à docência, o atendimento aos discentes, a participação no colegiado, o planejamento didático e a preparação e correção das avaliações de aprendizagem." },
    { concept: "4", criterion: "O regime de trabalho do corpo docente permite o atendimento integral da demanda existente, considerando a dedicação à docência, o atendimento aos discentes, a participação no colegiado, o planejamento didático e a preparação e correção das avaliações de aprendizagem, havendo documentação sobre as atividades dos professores em registros individuais de atividade docente." },
    { concept: "5", criterion: "O regime de trabalho do corpo docente permite o atendimento integral da demanda existente, considerando a dedicação à docência, o atendimento aos discentes, a participação no colegiado, o planejamento didático e a preparação e correção das avaliações de aprendizagem, havendo documentação sobre as atividades dos professores em registros individuais de atividade docente, utilizados no planejamento e gestão para melhoria contínua." }
  ],
  "2.7": [
    { concept: "1", criterion: "O corpo docente não possui experiência profissional no mundo do trabalho, ou a experiência não permite apresentar exemplos contextualizados com relação a problemas práticos." },
    { concept: "2", criterion: "O corpo docente possui experiência profissional no mundo do trabalho, que permite apresentar exemplos contextualizados com relação a problemas práticos, de aplicação da teoria ministrada em diferentes unidades curriculares em relação ao fazer profissional, mas não se atualizar com relação à interação conteúdo e prática." },
    { concept: "3", criterion: "O corpo docente possui experiência profissional no mundo do trabalho, que permite apresentar exemplos contextualizados com relação a problemas práticos, de aplicação da teoria ministrada em diferentes unidades curriculares em relação ao fazer profissional e atualizar-se com relação à interação conteúdo e prática." },
    { concept: "4", criterion: "O corpo docente possui experiência profissional no mundo do trabalho, que permite apresentar exemplos contextualizados com relação a problemas práticos, de aplicação da teoria ministrada em diferentes unidades curriculares em relação ao fazer profissional, atualizar-se com relação à interação conteúdo e prática, e promover compreensão da aplicação da interdisciplinaridade no contexto laboral." },
    { concept: "5", criterion: "O corpo docente possui experiência profissional no mundo do trabalho, que permite apresentar exemplos contextualizados com relação a problemas práticos, de aplicação da teoria ministrada em diferentes unidades curriculares em relação ao fazer profissional, atualizar-se com relação à interação conteúdo e prática, promover compreensão da aplicação da interdisciplinaridade no contexto laboral e analisar as competências previstas no PPC considerando o conteúdo abordado e a profissão." }
  ],
  "2.8": [
    { concept: "1", criterion: "O corpo docente não possui experiência na docência da educação básica, ou a experiência não permite identificar as dificuldades dos alunos ou expor o conteúdo em linguagem aderente às características da turma." },
    { concept: "2", criterion: "O corpo docente possui experiência na docência da educação básica para promover ações que permitem identificar as dificuldades dos alunos e expor o conteúdo em linguagem aderente às características da turma." },
    { concept: "3", criterion: "O corpo docente possui experiência na docência da educação básica para promover ações que permitem identificar as dificuldades dos alunos, expor o conteúdo em linguagem aderente às características da turma, apresentar exemplos contextualizados com os conteúdos dos componentes curriculares e elaborar atividades específicas para a promoção da aprendizagem de alunos com dificuldades." },
    { concept: "4", criterion: "O corpo docente possui experiência na docência da educação básica para promover ações que permitem identificar as dificuldades dos alunos, expor o conteúdo em linguagem aderente às características da turma, apresentar exemplos contextualizados com os conteúdos dos componentes curriculares, e elaborar atividades específicas para a promoção da aprendizagem de alunos com dificuldades e avaliações diagnósticas, formativas e somativas, utilizando os resultados para redefinição de sua prática docente no período." },
    { concept: "5", criterion: "O corpo docente possui experiência na docência da educação básica para promover ações que permitem identificar as dificuldades dos alunos, expor o conteúdo em linguagem aderente às características da turma, apresentar exemplos contextualizados com os conteúdos dos componentes curriculares, elaborar atividades específicas para a promoção da aprendizagem de alunos com dificuldades e avaliações diagnósticas, formativas e somativas, utilizando os resultados para redefinição de sua prática docente no período, exerce liderança e é reconhecido pela sua produção." }
  ],
  "2.9": [
    { concept: "1", criterion: "O corpo docente não possui experiência na docência superior, ou a experiência não permite identificar as dificuldades dos discentes ou expor o conteúdo em linguagem aderente às características da turma." },
    { concept: "2", criterion: "O corpo docente possui experiência na docência superior para promover ações que permitem identificar as dificuldades dos discentes e expor o conteúdo em linguagem aderente às características da turma, mas não apresentar exemplos contextualizados com os conteúdos dos componentes curriculares ou elaborar atividades específicas para a promoção da aprendizagem de discentes com dificuldades." },
    { concept: "3", criterion: "O corpo docente possui experiência na docência superior para promover ações que permitem identificar as dificuldades dos discentes, expor o conteúdo em linguagem aderente às características da turma, apresentar exemplos contextualizados com os conteúdos dos componentes curriculares e elaborar atividades específicas para a promoção da aprendizagem de discentes com dificuldades." },
    { concept: "4", criterion: "O corpo docente possui experiência na docência superior para promover ações que permitem identificar as dificuldades dos discentes, expor o conteúdo em linguagem aderente às características da turma, apresentar exemplos contextualizados com os conteúdos dos componentes curriculares, e elaborar atividades específicas para a promoção da aprendizagem de alunos com dificuldades e avaliações diagnósticas, formativas e somativas, utilizando os resultados para redefinição de sua prática docente no período." },
    { concept: "5", criterion: "O corpo docente possui experiência na docência superior para promover ações que permitem identificar as dificuldades dos discentes, expor o conteúdo em linguagem aderente às características da turma, apresentar exemplos contextualizados com os conteúdos dos componentes curriculares, e elaborar atividades específicas para a promoção da aprendizagem de discentes com dificuldades e avaliações diagnósticas, formativas e somativas, utilizando os resultados para redefinição de sua prática docente no período, exerce liderança e é reconhecido pela sua produção." }
  ],
  "2.10": [
    { concept: "1", criterion: "A experiência do corpo docente não permite identificar as dificuldades dos discentes ou expor o conteúdo em linguagem aderente às características da turma." },
    { concept: "2", criterion: "A experiência do corpo docente no exercício da docência na educação a distância permite identificar as dificuldades dos discentes, expor o conteúdo em linguagem aderente às características da turma, mas não apresentar exemplos contextualizados com os conteúdos dos componentes curriculares ou elaborar atividades específicas para a promoção da aprendizagem de discentes com dificuldades." },
    { concept: "3", criterion: "A experiência do corpo docente no exercício da docência na educação a distância permite identificar as dificuldades dos discentes, expor o conteúdo em linguagem aderente às características da turma, apresentar exemplos contextualizados com os conteúdos dos componentes curriculares e elaborar atividades específicas para a promoção da aprendizagem de discentes com dificuldades." },
    { concept: "4", criterion: "A experiência do corpo docente no exercício da docência na educação a distância permite identificar as dificuldades dos discentes, expor o conteúdo em linguagem aderente às características da turma, apresentar exemplos contextualizados com os conteúdos dos componentes curriculares, e elaborar atividades específicas para a promoção da aprendizagem de discentes com dificuldades e avaliações diagnósticas, formativas e somativas, utilizando os resultados para redefinição de sua prática docente no período." },
    { concept: "5", criterion: "A experiência do corpo docente no exercício da docência na educação a distância permite identificar as dificuldades dos discentes, expor o conteúdo em linguagem aderente às características da turma, apresentar exemplos contextualizados com os conteúdos dos componentes curriculares, e elaborar atividades específicas para a promoção da aprendizagem de discentes com dificuldades e avaliações diagnósticas, formativas e somativas, utilizando os resultados para redefinição de sua prática docente no período, exerce liderança e é reconhecido pela sua produção." }
  ],
  "2.11": [
    { concept: "1", criterion: "A experiência do corpo tutorial não permite fornecer suporte às atividades dos docentes." },
    { concept: "2", criterion: "A experiência do corpo tutorial permite fornecer suporte às atividades dos docentes, mas não realizar mediação pedagógica junto aos discentes." },
    { concept: "3", criterion: "A experiência do corpo tutorial permite fornecer suporte às atividades dos docentes e realizar mediação pedagógica junto aos discentes." },
    { concept: "4", criterion: "A experiência do corpo tutorial permite fornecer suporte às atividades dos docentes, realizar mediação pedagógica junto aos discentes e demonstrar inequívoca qualidade no relacionamento com os estudantes, incrementando processos de ensino aprendizagem." },
    { concept: "5", criterion: "A experiência do corpo tutorial permite fornecer suporte às atividades dos docentes, realizar mediação pedagógica junto aos discentes, demonstrar inequívoca qualidade no relacionamento com os estudantes, incrementando processos de ensino aprendizagem, e orientar os alunos, sugerindo atividades e leituras complementares que auxiliam sua formação." }
  ],
  "2.12": [
    { concept: "1", criterion: "A atuação do colegiado não está institucionalizada." },
    { concept: "2", criterion: "O colegiado atua e está institucionalizado, mas não possui representatividade dos segmentos; ou não se reúne com periodicidade determinada; ou as reuniões e as decisões associadas não são devidamente registradas; ou não há fluxo determinado para o encaminhamento das decisões." },
    { concept: "3", criterion: "O colegiado atua, está institucionalizado, possui representatividade dos segmentos, reúne-se com periodicidade determinada, sendo suas reuniões e as decisões associadas devidamente registradas, havendo um fluxo determinado para o encaminhamento das decisões." },
    { concept: "4", criterion: "O colegiado atua, está institucionalizado, possui representatividade dos segmentos, reúne-se com periodicidade determinada, sendo suas reuniões e as decisões associadas devidamente registradas, havendo um fluxo determinado para o encaminhamento das decisões, e dispõe de sistema de suporte ao registro, acompanhamento e execução de seus processos e decisões." },
    { concept: "5", criterion: "O colegiado atua, está institucionalizado, possui representatividade dos segmentos, reúne-se com periodicidade determinada, sendo suas reuniões e as decisões associadas devidamente registradas, havendo um fluxo determinado para o encaminhamento das decisões, dispõe de sistema de suporte ao registro, acompanhamento e execução de seus processos e decisões e realiza avaliação periódica sobre seu desempenho, para implementação ou ajuste de práticas de gestão." }
  ],
  "2.13": [
    { concept: "1", criterion: "Nenhum tutor é graduado na área da disciplina pela qual é responsável." },
    { concept: "2", criterion: "Parte dos tutores é graduada na área da disciplina pelas quais são responsáveis." },
    { concept: "3", criterion: "Todos os tutores são graduados na área da disciplina pelas quais são responsáveis." },
    { concept: "4", criterion: "Todos os tutores são graduados na área da disciplina pelas quais são responsáveis e a maioria possui titulação obtida em pós-graduação lato sensu." },
    { concept: "5", criterion: "Todos os tutores são graduados na área da disciplina pelas quais são responsáveis e a maioria possui titulação obtida em pós-graduação em stricto sensu." }
  ],
  "2.14": [
    { concept: "1", criterion: "O corpo de tutores não possui experiência em educação a distância não permite identificar as dificuldades dos alunos ou expor o conteúdo em linguagem aderente às características da turma." },
    { concept: "2", criterion: "O corpo de tutores possui experiência em educação a distância, que permite identificar as dificuldades dos discentes e expor o conteúdo em linguagem aderente às características da turma, mas não apresentar exemplos contextualizados com os conteúdos dos componentes curriculares." },
    { concept: "3", criterion: "O corpo de tutores possui experiência em educação a distância que permite identificar as dificuldades dos discentes, expor o conteúdo em linguagem aderente às características da turma e apresentar exemplos contextualizados com os conteúdos dos componentes curriculares." },
    { concept: "4", criterion: "O corpo de tutores possui experiência em educação a distância que permite identificar as dificuldades dos discentes, expor o conteúdo em linguagem aderente às características da turma, apresentar exemplos contextualizados com os conteúdos dos componentes curriculares e elaborar atividades específicas, em colaboração com os docentes, para a promoção da aprendizagem de alunos com dificuldades." },
    { concept: "5", criterion: "O corpo de tutores possui experiência em educação a distância que permite identificar as dificuldades dos discentes, expor o conteúdo em linguagem aderente às características da turma, apresentar exemplos contextualizados com os conteúdos dos componentes curriculares e elaborar atividades específicas, em colaboração com os docentes, para a promoção da aprendizagem de alunos com dificuldades, e adota práticas comprovadamente exitosas ou inovadoras no contexto da modalidade a distância." }
  ],
  "2.15": [
    { concept: "1", criterion: "Não há interação, explicitada no PPC, para garantir a mediação ou a articulação entre tutores, docentes e coordenador do curso." },
    { concept: "2", criterion: "Há interação, explicitada no PPC, que não garante a mediação ou a articulação entre tutores, docentes e coordenador do curso." },
    { concept: "3", criterion: "Há interação, explicitada no PPC, que garante a mediação e a articulação entre tutores, docentes e coordenador do curso." },
    { concept: "4", criterion: "Há interação, explicitada no PPC, que garante a mediação e a articulação entre tutores, docentes e coordenador do curso e há planejamento devidamente documentado de interação para encaminhamento de questões do curso." },
    { concept: "5", criterion: "Há interação, explicitada no PPC, que garante a mediação e a articulação entre tutores, docentes e coordenador do curso (e, quando for o caso, coordenador do polo), há planejamento devidamente documentado de interação para encaminhamento de questões do curso, e são realizadas avaliações periódicas para a identificação de problemas ou incremento na interação entre os interlocutores." }
  ],
  "2.16": [
    { concept: "1", criterion: "Mais de 50% dos docentes não possuem produção nos últimos 3 anos." },
    { concept: "2", criterion: "Pelo menos 50% dos docentes possuem, no mínimo, 1 produção nos últimos 3 anos." },
    { concept: "3", criterion: "Pelo menos 50% dos docentes possuem, no mínimo, 4 produções nos últimos 3 anos." },
    { concept: "4", criterion: "Pelo menos 50% dos docentes possuem, no mínimo, 7 produções nos últimos 3 anos." },
    { concept: "5", criterion: "Pelo menos 50% dos docentes possuem, no mínimo, 9 produções nos últimos 3 anos." }
  ]
};
